INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (1, 20,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (1, 30,'ON');

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (2, 10,'OFF');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (2, 30,'OFF');

INSERT INTO LIGHT (ID, LEVEL, STATUS) VALUES (3, 100,'ON');
INSERT INTO NOISE (ID, LEVEL, STATUS) VALUES (3, 300,'ON');

INSERT INTO BUILDING (ID, NAME, STATUS) VALUES (1, 30,'ON');

INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID, BUILDING_ID) VALUES (1, 1, 1, 1);
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID, BUILDING_ID) VALUES (2, 2, 2, 1);
INSERT INTO ROOM (ID, LIGHT_ID, NOISE_ID, BUILDING_ID) VALUES (3, 3, 3, 1);


